"""followers auxilliary table

Revision ID: 77276eb5a8a2
Revises: 02826359d99c
Create Date: 2024-08-27 12:02:08.616681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77276eb5a8a2'
down_revision = '02826359d99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
